#!/bin/bash

exec docker run \
     --volume "$PWD:/app/volume" \
     --interactive --tty --rm \
     --user "$(id -u):$(id -g)" \
    "utulsa/wpe-tool:latest" /usr/local/bin/python3 entrypoint.py "$@"
