stages:
  - deploy

deploy to wpengine staging:
  type: deploy
  image: utulsa/wpe-deploy:latest
  environment:
    name: wpe-staging
    url: ${staging__url}
  only:
    - staging
  variables:
    WPE_REMOTE_URL: ${staging__git_remote}
    GIT_SUBMODULE_STRATEGY: recursive
  before_script:
    - source setup-ssh
    - git submodule sync --recursive
    - git submodule update --init --recursive
  script:
    - run-deploy

deploy to wpengine prod:
  type: deploy
  image: utulsa/wpe-deploy:latest
  only:
    - production
  environment:
    name: wpe-production
    url: ${prod__url}
  variables:
    WPE_REMOTE_URL: ${prod__git_remote}
    GIT_SUBMODULE_STRATEGY: recursive
  before_script:
    - source setup-ssh
    - git submodule sync --recursive
    - git submodule update --init --recursive
  script:
    - run-deploy
