version: '3.0'
services:
  wordpress:
    image: utulsa/wordpress:latest
    links:
      - db:db
    environment:
      VIRTUAL_HOST: "${virtual_hosts}"
      DB_HOST: "db"
      DB_NAME: "wp"
      DB_USER: "root"
      DB_PASSWORD: "root"
      DB_CHARSET: "${wp_db_charset}"
      DB_COLLATE: "${wp_db_collate}"
      TABLE_PREFIX: "${wp_table_prefix}"
      MULTISITE_CONFIG: "${wp_multisite_config}"
    volumes:
      - ./.htaccess:/var/www/html/.htaccess
      - ./wp-config-extra.php:/var/www/html/wp-config-extra.php
      - ./wp-content/debug.log:/var/www/html/wp-content/debug.log
      - ./wp-content/plugins:/var/www/html/wp-content/plugins
      - ./wp-content/themes:/var/www/html/wp-content/themes
      - ./wp-content/uploads:/var/www/html/wp-content/uploads
    restart: "no"
    network_mode: "bridge"
  db:
    image: mariadb:10
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wp
      MYSQL_USER: utulsa
      MYSQL_PASSWORD: utulsa
    volumes:
      - ./.db/mysql.sql:/docker-entrypoint-initdb.d/mysql.sql
    restart: unless-stopped
    network_mode: "bridge"
    restart: "no"
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    links:
      - db:db
    environment:
      VIRTUAL_HOST: "${phpmyadmin_virtual_host}"
    restart: "no"
    network_mode: "bridge"
